### Create a valid daily journal

POST localhost:30000/api/v1/journals/2026-07-19
Authorization: Bearer {{loginToken}}

{
    "note":"Productive day"
}

###

### Reject a journal with domain validation errors

POST localhost:30000/api/v1/journals/1999-12-31
Authorization: Bearer {{loginToken}}

{
    "note":"Invalid\u0008note"
}
