### Create a valid daily journal

POST localhost:30000/api/v1/journals
Authorization: Bearer {{loginToken}}

{
    "date":"2026-07-15",
    "mood":3,
    "note":"Productive day"
}

###

### Reject a journal with domain validation errors

POST localhost:30000/api/v1/journals
Authorization: Bearer {{loginToken}}

{
    "date":"1999-12-31",
    "mood":6,
    "note":"Invalid\u0008note"
}
