### Create transaction
POST localhost:30000/api/v1/transactions
Authorization: Bearer {{loginToken}}
Content-Type: application/json

{
  "money": 1250.5,
  "date": "2000-01-01",
  "category": 2,
  "description": "Coffee with team"
}
