### Save or update a time habit record for a specific day.

POST localhost:30000/api/v1/habits/time/{{habitId}}/2000-01-01
Authorization: Bearer {{loginToken}}
Content-Type: application/json

{
    "value": 480
}
