export const EmojiIcons = {
    Favorite: 1,
    HealthAndSafety: 2,
    HealthMetrics: 3,
    MedicalServices: 4,
    MedicalInformation: 5,
    Medication: 6,
    Pill: 7,
    Vaccines: 8,
    Dentistry: 9,
    Stethoscope: 10,
    Cardiology: 11,
    MonitorHeart: 12,
    BloodPressure: 13,
    Thermometer: 14,
    Bed: 15,
    Bedtime: 16,
    Sleep: 17,
    SleepScore: 18,
    Shower: 19,
    Bathtub: 20,
    CleanHands: 21,
    Sanitizer: 22,
    Scale: 23,
    MonitorWeight: 24,
    FitnessCenter: 25,
    Exercise: 26,
    DirectionsRun: 27,
    Sprint: 28,
    DirectionsWalk: 29,
    NordicWalking: 30,
    Hiking: 31,
    DirectionsBike: 32,
    PedalBike: 33,
    Pool: 34,
    Rowing: 35,
    SportsGymnastics: 36,
    SportsMartialArts: 37,
    SportsSoccer: 38,
    SportsBasketball: 39,
    SportsTennis: 40,
    SportsVolleyball: 41,
    SportsHandball: 42,
    SportsFootball: 43,
    SportsRugby: 44,
    SportsGolf: 45,
    SportsBaseball: 46,
    Skateboarding: 47,
    Surfing: 48,
    WaterDrop: 49,
    WaterBottle: 50,
    LocalDrink: 51,
    Coffee: 52,
    CoffeeMaker: 53,
    EmojiFoodBeverage: 54,
    Nutrition: 55,
    Restaurant: 56,
    RestaurantMenu: 57,
    LocalDining: 58,
    DinnerDining: 59,
    LunchDining: 60,
    BreakfastDining: 61,
    Fastfood: 62,
    Grocery: 63,
    LocalGroceryStore: 64,
    Cooking: 65,
    SkilletCooktop: 66,
    BakeryDining: 67,
    Cake: 68,
    Egg: 69,
    RiceBowl: 70,
    RamenDining: 71,
    Icecream: 72,
    Home: 73,
    HomeAndGarden: 74,
    CleaningServices: 75,
    Cleaning: 76,
    CleaningBucket: 77,
    Mop: 78,
    Wash: 79,
    Laundry: 80,
    LocalLaundryService: 81,
    Dishwasher: 82,
    Kitchen: 83,
    Vacuum: 84,
    Iron: 85,
    PottedPlant: 86,
    OutdoorGarden: 87,
    HomeRepairService: 88,
    HomeImprovementAndTools: 89,
    ToolsPowerDrill: 90,
    ToolsWrench: 91,
    ToolsLadder: 92,
    Chair: 93,
    Garage: 94,
    DoorFront: 95,
    Window: 96,
    Work: 97,
    Laptop: 98,
    Computer: 99,
    Terminal: 100,
    Code: 101,
    CodeBlocks: 102,
    DataObject: 103,
    Book: 104,
    MenuBook: 105,
    LibraryBooks: 106,
    School: 107,
    Language: 108,
    Translate: 109,
    Science: 110,
    Calculate: 111,
    EditNote: 112,
    TaskAlt: 113,
    Checklist: 114,
    CalendarMonth: 115,
    Schedule: 116,
    Lightbulb: 117,
    Psychology: 118,
    Draw: 119,
    DesignServices: 120,
    MusicNote: 121,
    Headphones: 122,
    LibraryMusic: 123,
    Piano: 124,
    Palette: 125,
    Brush: 126,
    VideogameAsset: 127,
    Games: 128,
    Movie: 129,
    Theaters: 130,
    PhotoCamera: 131,
    TravelExplore: 132,
    Sunny: 133,
    SelfImprovement: 134,
    Spa: 135,
    Mood: 136,
    Nature: 137,
    Forest: 138,
    Park: 139,
    BeachAccess: 140,
    Fireplace: 141,
    Celebration: 142,
    Pets: 143,
    Camping: 144,
} as const

export type EmojiIcon = (typeof EmojiIcons)[keyof typeof EmojiIcons]

export type EmojiIconSection = {
    name: string
    icons: Array<{ icon: EmojiIcon; label: string }>
}

export const emojiIconNames: Record<EmojiIcon, string> = {
    [EmojiIcons.Favorite]: '❤️',
    [EmojiIcons.HealthAndSafety]: '🛡️',
    [EmojiIcons.HealthMetrics]: '📊',
    [EmojiIcons.MedicalServices]: '🏥',
    [EmojiIcons.MedicalInformation]: '📋',
    [EmojiIcons.Medication]: '💊',
    [EmojiIcons.Pill]: '🩹',
    [EmojiIcons.Vaccines]: '💉',
    [EmojiIcons.Dentistry]: '🦷',
    [EmojiIcons.Stethoscope]: '🩺',
    [EmojiIcons.Cardiology]: '🫀',
    [EmojiIcons.MonitorHeart]: '💓',
    [EmojiIcons.BloodPressure]: '🩸',
    [EmojiIcons.Thermometer]: '🌡️',
    [EmojiIcons.Bed]: '🛏️',
    [EmojiIcons.Bedtime]: '🌙',
    [EmojiIcons.Sleep]: '😴',
    [EmojiIcons.SleepScore]: '💤',
    [EmojiIcons.Shower]: '🚿',
    [EmojiIcons.Bathtub]: '🛁',
    [EmojiIcons.CleanHands]: '🧼',
    [EmojiIcons.Sanitizer]: '🧴',
    [EmojiIcons.Scale]: '⚖️',
    [EmojiIcons.MonitorWeight]: '📉',
    [EmojiIcons.FitnessCenter]: '🏋️',
    [EmojiIcons.Exercise]: '🤸',
    [EmojiIcons.DirectionsRun]: '🏃',
    [EmojiIcons.Sprint]: '⚡',
    [EmojiIcons.DirectionsWalk]: '🚶',
    [EmojiIcons.NordicWalking]: '🥾',
    [EmojiIcons.Hiking]: '⛰️',
    [EmojiIcons.DirectionsBike]: '🚴',
    [EmojiIcons.PedalBike]: '🚲',
    [EmojiIcons.Pool]: '🏊',
    [EmojiIcons.Rowing]: '🚣',
    [EmojiIcons.SportsGymnastics]: '🤸‍♀️',
    [EmojiIcons.SportsMartialArts]: '🥋',
    [EmojiIcons.SportsSoccer]: '⚽',
    [EmojiIcons.SportsBasketball]: '🏀',
    [EmojiIcons.SportsTennis]: '🎾',
    [EmojiIcons.SportsVolleyball]: '🏐',
    [EmojiIcons.SportsHandball]: '🤾',
    [EmojiIcons.SportsFootball]: '🏈',
    [EmojiIcons.SportsRugby]: '🏉',
    [EmojiIcons.SportsGolf]: '⛳',
    [EmojiIcons.SportsBaseball]: '⚾',
    [EmojiIcons.Skateboarding]: '🛹',
    [EmojiIcons.Surfing]: '🏄',
    [EmojiIcons.WaterDrop]: '💧',
    [EmojiIcons.WaterBottle]: '🥤',
    [EmojiIcons.LocalDrink]: '🥛',
    [EmojiIcons.Coffee]: '☕',
    [EmojiIcons.CoffeeMaker]: '🫖',
    [EmojiIcons.EmojiFoodBeverage]: '🍵',
    [EmojiIcons.Nutrition]: '🥗',
    [EmojiIcons.Restaurant]: '🍽️',
    [EmojiIcons.RestaurantMenu]: '📜',
    [EmojiIcons.LocalDining]: '🍴',
    [EmojiIcons.DinnerDining]: '🥘',
    [EmojiIcons.LunchDining]: '🥪',
    [EmojiIcons.BreakfastDining]: '🍳',
    [EmojiIcons.Fastfood]: '🍔',
    [EmojiIcons.Grocery]: '🛒',
    [EmojiIcons.LocalGroceryStore]: '🏪',
    [EmojiIcons.Cooking]: '🧑‍🍳',
    [EmojiIcons.SkilletCooktop]: '🔥',
    [EmojiIcons.BakeryDining]: '🥐',
    [EmojiIcons.Cake]: '🎂',
    [EmojiIcons.Egg]: '🥚',
    [EmojiIcons.RiceBowl]: '🍚',
    [EmojiIcons.RamenDining]: '🍜',
    [EmojiIcons.Icecream]: '🍨',
    [EmojiIcons.Home]: '🏠',
    [EmojiIcons.HomeAndGarden]: '🏡',
    [EmojiIcons.CleaningServices]: '🧹',
    [EmojiIcons.Cleaning]: '✨',
    [EmojiIcons.CleaningBucket]: '🪣',
    [EmojiIcons.Mop]: '🧽',
    [EmojiIcons.Wash]: '🧼',
    [EmojiIcons.Laundry]: '🧺',
    [EmojiIcons.LocalLaundryService]: '👕',
    [EmojiIcons.Dishwasher]: '🍽️',
    [EmojiIcons.Kitchen]: '🍳',
    [EmojiIcons.Vacuum]: '🌪️',
    [EmojiIcons.Iron]: '👔',
    [EmojiIcons.PottedPlant]: '🪴',
    [EmojiIcons.OutdoorGarden]: '🌻',
    [EmojiIcons.HomeRepairService]: '🔧',
    [EmojiIcons.HomeImprovementAndTools]: '🛠️',
    [EmojiIcons.ToolsPowerDrill]: '🪛',
    [EmojiIcons.ToolsWrench]: '⚙️',
    [EmojiIcons.ToolsLadder]: '🪜',
    [EmojiIcons.Chair]: '🪑',
    [EmojiIcons.Garage]: '🚗',
    [EmojiIcons.DoorFront]: '🚪',
    [EmojiIcons.Window]: '🪟',
    [EmojiIcons.Work]: '💼',
    [EmojiIcons.Laptop]: '💻',
    [EmojiIcons.Computer]: '🖥️',
    [EmojiIcons.Terminal]: '⌨️',
    [EmojiIcons.Code]: '🧑‍💻',
    [EmojiIcons.CodeBlocks]: '🧩',
    [EmojiIcons.DataObject]: '🗃️',
    [EmojiIcons.Book]: '📘',
    [EmojiIcons.MenuBook]: '📖',
    [EmojiIcons.LibraryBooks]: '📚',
    [EmojiIcons.School]: '🎓',
    [EmojiIcons.Language]: '🌐',
    [EmojiIcons.Translate]: '🔤',
    [EmojiIcons.Science]: '🔬',
    [EmojiIcons.Calculate]: '🧮',
    [EmojiIcons.EditNote]: '📝',
    [EmojiIcons.TaskAlt]: '✅',
    [EmojiIcons.Checklist]: '☑️',
    [EmojiIcons.CalendarMonth]: '📅',
    [EmojiIcons.Schedule]: '⏰',
    [EmojiIcons.Lightbulb]: '💡',
    [EmojiIcons.Psychology]: '🧠',
    [EmojiIcons.Draw]: '✏️',
    [EmojiIcons.DesignServices]: '🎨',
    [EmojiIcons.MusicNote]: '🎵',
    [EmojiIcons.Headphones]: '🎧',
    [EmojiIcons.LibraryMusic]: '🎶',
    [EmojiIcons.Piano]: '🎹',
    [EmojiIcons.Palette]: '🎨',
    [EmojiIcons.Brush]: '🖌️',
    [EmojiIcons.VideogameAsset]: '🎮',
    [EmojiIcons.Games]: '🕹️',
    [EmojiIcons.Movie]: '🎬',
    [EmojiIcons.Theaters]: '🍿',
    [EmojiIcons.PhotoCamera]: '📷',
    [EmojiIcons.TravelExplore]: '🧭',
    [EmojiIcons.Sunny]: '☀️',
    [EmojiIcons.SelfImprovement]: '🧘',
    [EmojiIcons.Spa]: '💆',
    [EmojiIcons.Mood]: '🙂',
    [EmojiIcons.Nature]: '🌿',
    [EmojiIcons.Forest]: '🌲',
    [EmojiIcons.Park]: '🌳',
    [EmojiIcons.BeachAccess]: '🏖️',
    [EmojiIcons.Fireplace]: '🔥',
    [EmojiIcons.Celebration]: '🎉',
    [EmojiIcons.Pets]: '🐾',
    [EmojiIcons.Camping]: '⛺',
}

export const emojiIconSections: EmojiIconSection[] = [
    {
        name: 'Health',
        icons: [
            { icon: EmojiIcons.Favorite, label: 'Общее здоровье' },
            { icon: EmojiIcons.HealthAndSafety, label: 'Защита и иммунитет' },
            { icon: EmojiIcons.HealthMetrics, label: 'Показатели здоровья' },
            { icon: EmojiIcons.MedicalServices, label: 'Врач или клиника' },
            { icon: EmojiIcons.MedicalInformation, label: 'Медицинская информация' },
            { icon: EmojiIcons.Medication, label: 'Лекарства' },
            { icon: EmojiIcons.Pill, label: 'Лечение' },
            { icon: EmojiIcons.Vaccines, label: 'Вакцинация' },
            { icon: EmojiIcons.Dentistry, label: 'Зубы' },
            { icon: EmojiIcons.Stethoscope, label: 'Осмотр врача' },
            { icon: EmojiIcons.Cardiology, label: 'Сердце' },
            { icon: EmojiIcons.MonitorHeart, label: 'Пульс' },
            { icon: EmojiIcons.BloodPressure, label: 'Кровь и давление' },
            { icon: EmojiIcons.Thermometer, label: 'Температура' },
            { icon: EmojiIcons.Bed, label: 'Постель' },
            { icon: EmojiIcons.Bedtime, label: 'Отход ко сну' },
            { icon: EmojiIcons.Sleep, label: 'Сон' },
            { icon: EmojiIcons.SleepScore, label: 'Качество сна' },
            { icon: EmojiIcons.Shower, label: 'Душ' },
            { icon: EmojiIcons.Bathtub, label: 'Ванна' },
            { icon: EmojiIcons.CleanHands, label: 'Мытьё рук' },
            { icon: EmojiIcons.Sanitizer, label: 'Гигиена' },
            { icon: EmojiIcons.Scale, label: 'Вес' },
            { icon: EmojiIcons.MonitorWeight, label: 'Изменение веса' },
        ],
    },
    {
        name: 'Sports and Movement',
        icons: [
            { icon: EmojiIcons.FitnessCenter, label: 'Силовая тренировка' },
            { icon: EmojiIcons.Exercise, label: 'Упражнения' },
            { icon: EmojiIcons.DirectionsRun, label: 'Бег' },
            { icon: EmojiIcons.Sprint, label: 'Спринт' },
            { icon: EmojiIcons.DirectionsWalk, label: 'Ходьба' },
            { icon: EmojiIcons.NordicWalking, label: 'Долгая прогулка' },
            { icon: EmojiIcons.Hiking, label: 'Поход' },
            { icon: EmojiIcons.DirectionsBike, label: 'Велотренировка' },
            { icon: EmojiIcons.PedalBike, label: 'Велосипед' },
            { icon: EmojiIcons.Pool, label: 'Плавание' },
            { icon: EmojiIcons.Rowing, label: 'Гребля' },
            { icon: EmojiIcons.SportsGymnastics, label: 'Гимнастика' },
            { icon: EmojiIcons.SportsMartialArts, label: 'Единоборства' },
            { icon: EmojiIcons.SportsSoccer, label: 'Футбол' },
            { icon: EmojiIcons.SportsBasketball, label: 'Баскетбол' },
            { icon: EmojiIcons.SportsTennis, label: 'Теннис' },
            { icon: EmojiIcons.SportsVolleyball, label: 'Волейбол' },
            { icon: EmojiIcons.SportsHandball, label: 'Гандбол' },
            { icon: EmojiIcons.SportsFootball, label: 'Американский футбол' },
            { icon: EmojiIcons.SportsRugby, label: 'Регби' },
            { icon: EmojiIcons.SportsGolf, label: 'Гольф' },
            { icon: EmojiIcons.SportsBaseball, label: 'Бейсбол' },
            { icon: EmojiIcons.Skateboarding, label: 'Скейтборд' },
            { icon: EmojiIcons.Surfing, label: 'Сёрфинг' },
        ],
    },
    {
        name: 'Food and Drinks',
        icons: [
            { icon: EmojiIcons.WaterDrop, label: 'Вода' },
            { icon: EmojiIcons.WaterBottle, label: 'Напиток' },
            { icon: EmojiIcons.LocalDrink, label: 'Молоко' },
            { icon: EmojiIcons.Coffee, label: 'Кофе' },
            { icon: EmojiIcons.CoffeeMaker, label: 'Чай' },
            { icon: EmojiIcons.EmojiFoodBeverage, label: 'Горячий напиток' },
            { icon: EmojiIcons.Nutrition, label: 'Здоровое питание' },
            { icon: EmojiIcons.Restaurant, label: 'Приём пищи' },
            { icon: EmojiIcons.RestaurantMenu, label: 'Меню или рацион' },
            { icon: EmojiIcons.LocalDining, label: 'Еда' },
            { icon: EmojiIcons.DinnerDining, label: 'Ужин' },
            { icon: EmojiIcons.LunchDining, label: 'Обед' },
            { icon: EmojiIcons.BreakfastDining, label: 'Завтрак' },
            { icon: EmojiIcons.Fastfood, label: 'Фастфуд' },
            { icon: EmojiIcons.Grocery, label: 'Покупка продуктов' },
            { icon: EmojiIcons.LocalGroceryStore, label: 'Магазин' },
            { icon: EmojiIcons.Cooking, label: 'Готовка' },
            { icon: EmojiIcons.SkilletCooktop, label: 'Приготовление на плите' },
            { icon: EmojiIcons.BakeryDining, label: 'Выпечка' },
            { icon: EmojiIcons.Cake, label: 'Сладкое' },
            { icon: EmojiIcons.Egg, label: 'Яйца' },
            { icon: EmojiIcons.RiceBowl, label: 'Рис или крупы' },
            { icon: EmojiIcons.RamenDining, label: 'Лапша' },
            { icon: EmojiIcons.Icecream, label: 'Мороженое' },
        ],
    },
    {
        name: 'Home and Household',
        icons: [
            { icon: EmojiIcons.Home, label: 'Дом' },
            { icon: EmojiIcons.HomeAndGarden, label: 'Дом и участок' },
            { icon: EmojiIcons.CleaningServices, label: 'Уборка' },
            { icon: EmojiIcons.Cleaning, label: 'Наведение порядка' },
            { icon: EmojiIcons.CleaningBucket, label: 'Влажная уборка' },
            { icon: EmojiIcons.Mop, label: 'Мытьё поверхностей' },
            { icon: EmojiIcons.Wash, label: 'Мытьё' },
            { icon: EmojiIcons.Laundry, label: 'Стирка' },
            { icon: EmojiIcons.LocalLaundryService, label: 'Уход за одеждой' },
            { icon: EmojiIcons.Dishwasher, label: 'Посуда' },
            { icon: EmojiIcons.Kitchen, label: 'Кухня' },
            { icon: EmojiIcons.Vacuum, label: 'Пылесос' },
            { icon: EmojiIcons.Iron, label: 'Глажка' },
            { icon: EmojiIcons.PottedPlant, label: 'Комнатные растения' },
            { icon: EmojiIcons.OutdoorGarden, label: 'Сад' },
            { icon: EmojiIcons.HomeRepairService, label: 'Ремонт' },
            { icon: EmojiIcons.HomeImprovementAndTools, label: 'Домашние работы' },
            { icon: EmojiIcons.ToolsPowerDrill, label: 'Инструменты' },
            { icon: EmojiIcons.ToolsWrench, label: 'Обслуживание' },
            { icon: EmojiIcons.ToolsLadder, label: 'Лестница и высотные работы' },
            { icon: EmojiIcons.Chair, label: 'Мебель' },
            { icon: EmojiIcons.Garage, label: 'Гараж' },
            { icon: EmojiIcons.DoorFront, label: 'Двери' },
            { icon: EmojiIcons.Window, label: 'Окна' },
        ],
    },
    {
        name: 'Work and Growth',
        icons: [
            { icon: EmojiIcons.Work, label: 'Работа' },
            { icon: EmojiIcons.Laptop, label: 'Ноутбук' },
            { icon: EmojiIcons.Computer, label: 'Компьютер' },
            { icon: EmojiIcons.Terminal, label: 'Терминал' },
            { icon: EmojiIcons.Code, label: 'Программирование' },
            { icon: EmojiIcons.CodeBlocks, label: 'Решение задач' },
            { icon: EmojiIcons.DataObject, label: 'Данные' },
            { icon: EmojiIcons.Book, label: 'Чтение' },
            { icon: EmojiIcons.MenuBook, label: 'Книга' },
            { icon: EmojiIcons.LibraryBooks, label: 'Обучение' },
            { icon: EmojiIcons.School, label: 'Учёба' },
            { icon: EmojiIcons.Language, label: 'Иностранный язык' },
            { icon: EmojiIcons.Translate, label: 'Перевод' },
            { icon: EmojiIcons.Science, label: 'Наука' },
            { icon: EmojiIcons.Calculate, label: 'Вычисления' },
            { icon: EmojiIcons.EditNote, label: 'Заметки' },
            { icon: EmojiIcons.TaskAlt, label: 'Выполненная задача' },
            { icon: EmojiIcons.Checklist, label: 'Список дел' },
            { icon: EmojiIcons.CalendarMonth, label: 'Календарь' },
            { icon: EmojiIcons.Schedule, label: 'Расписание' },
            { icon: EmojiIcons.Lightbulb, label: 'Новая идея' },
            { icon: EmojiIcons.Psychology, label: 'Мышление' },
            { icon: EmojiIcons.Draw, label: 'Рисование' },
            { icon: EmojiIcons.DesignServices, label: 'Дизайн' },
        ],
    },
    {
        name: 'Rest and Well-being',
        icons: [
            { icon: EmojiIcons.MusicNote, label: 'Музыка' },
            { icon: EmojiIcons.Headphones, label: 'Прослушивание музыки' },
            { icon: EmojiIcons.LibraryMusic, label: 'Плейлист' },
            { icon: EmojiIcons.Piano, label: 'Музыкальный инструмент' },
            { icon: EmojiIcons.Palette, label: 'Творчество' },
            { icon: EmojiIcons.Brush, label: 'Рисование' },
            { icon: EmojiIcons.VideogameAsset, label: 'Видеоигры' },
            { icon: EmojiIcons.Games, label: 'Игры' },
            { icon: EmojiIcons.Movie, label: 'Кино' },
            { icon: EmojiIcons.Theaters, label: 'Просмотр фильма' },
            { icon: EmojiIcons.PhotoCamera, label: 'Фотография' },
            { icon: EmojiIcons.TravelExplore, label: 'Исследование новых мест' },
            { icon: EmojiIcons.Sunny, label: 'Время на солнце' },
            { icon: EmojiIcons.SelfImprovement, label: 'Медитация' },
            { icon: EmojiIcons.Spa, label: 'Уход за собой' },
            { icon: EmojiIcons.Mood, label: 'Настроение' },
            { icon: EmojiIcons.Nature, label: 'Природа' },
            { icon: EmojiIcons.Forest, label: 'Лес' },
            { icon: EmojiIcons.Park, label: 'Парк' },
            { icon: EmojiIcons.BeachAccess, label: 'Пляж' },
            { icon: EmojiIcons.Fireplace, label: 'Уют и отдых' },
            { icon: EmojiIcons.Celebration, label: 'Праздник' },
            { icon: EmojiIcons.Pets, label: 'Питомцы' },
            { icon: EmojiIcons.Camping, label: 'Поход и кемпинг' },
        ],
    },
]

export const GoogleIcons = EmojiIcons
export type GoogleIcons = EmojiIcon
export const googleIconNames = emojiIconNames
export const googleIconSections = emojiIconSections
