export const GoogleIcons = {
    Favorite: 1,
    HealthAndSafety: 2,
    HealthMetrics: 3,
    MedicalServices: 4,
    MedicalInformation: 5,
    Medication: 6,
    Pill: 7,
    Vaccines: 8,
    Dentistry: 9,
    Stethoscope: 10,
    Cardiology: 11,
    MonitorHeart: 12,
    BloodPressure: 13,
    Thermometer: 14,
    Bed: 15,
    Bedtime: 16,
    Sleep: 17,
    SleepScore: 18,
    Shower: 19,
    Bathtub: 20,
    CleanHands: 21,
    Sanitizer: 22,
    Scale: 23,
    MonitorWeight: 24,
    FitnessCenter: 25,
    Exercise: 26,
    DirectionsRun: 27,
    Sprint: 28,
    DirectionsWalk: 29,
    NordicWalking: 30,
    Hiking: 31,
    DirectionsBike: 32,
    PedalBike: 33,
    Pool: 34,
    Rowing: 35,
    SportsGymnastics: 36,
    SportsMartialArts: 37,
    SportsSoccer: 38,
    SportsBasketball: 39,
    SportsTennis: 40,
    SportsVolleyball: 41,
    SportsHandball: 42,
    SportsFootball: 43,
    SportsRugby: 44,
    SportsGolf: 45,
    SportsBaseball: 46,
    Skateboarding: 47,
    Surfing: 48,
    WaterDrop: 49,
    WaterBottle: 50,
    LocalDrink: 51,
    Coffee: 52,
    CoffeeMaker: 53,
    EmojiFoodBeverage: 54,
    Nutrition: 55,
    Restaurant: 56,
    RestaurantMenu: 57,
    LocalDining: 58,
    DinnerDining: 59,
    LunchDining: 60,
    BreakfastDining: 61,
    Fastfood: 62,
    Grocery: 63,
    LocalGroceryStore: 64,
    Cooking: 65,
    SkilletCooktop: 66,
    BakeryDining: 67,
    Cake: 68,
    Egg: 69,
    RiceBowl: 70,
    RamenDining: 71,
    Icecream: 72,
    Home: 73,
    HomeAndGarden: 74,
    CleaningServices: 75,
    Cleaning: 76,
    CleaningBucket: 77,
    Mop: 78,
    Wash: 79,
    Laundry: 80,
    LocalLaundryService: 81,
    Dishwasher: 82,
    Kitchen: 83,
    Vacuum: 84,
    Iron: 85,
    PottedPlant: 86,
    OutdoorGarden: 87,
    HomeRepairService: 88,
    HomeImprovementAndTools: 89,
    ToolsPowerDrill: 90,
    ToolsWrench: 91,
    ToolsLadder: 92,
    Chair: 93,
    Garage: 94,
    DoorFront: 95,
    Window: 96,
    Work: 97,
    Laptop: 98,
    Computer: 99,
    Terminal: 100,
    Code: 101,
    CodeBlocks: 102,
    DataObject: 103,
    Book: 104,
    MenuBook: 105,
    LibraryBooks: 106,
    School: 107,
    Language: 108,
    Translate: 109,
    Science: 110,
    Calculate: 111,
    EditNote: 112,
    TaskAlt: 113,
    Checklist: 114,
    CalendarMonth: 115,
    Schedule: 116,
    Lightbulb: 117,
    Psychology: 118,
    Draw: 119,
    DesignServices: 120,
    MusicNote: 121,
    Headphones: 122,
    LibraryMusic: 123,
    Piano: 124,
    Palette: 125,
    Brush: 126,
    VideogameAsset: 127,
    Games: 128,
    Movie: 129,
    Theaters: 130,
    PhotoCamera: 131,
    TravelExplore: 132,
    Sunny: 133,
    SelfImprovement: 134,
    Spa: 135,
    Mood: 136,
    Nature: 137,
    Forest: 138,
    Park: 139,
    BeachAccess: 140,
    Fireplace: 141,
    Celebration: 142,
    Pets: 143,
    Camping: 144,
} as const

export type GoogleIcons = (typeof GoogleIcons)[keyof typeof GoogleIcons]

export const googleIconNames: Record<GoogleIcons, string> = {
    [GoogleIcons.Favorite]: "favorite",
    [GoogleIcons.HealthAndSafety]: "health_and_safety",
    [GoogleIcons.HealthMetrics]: "health_metrics",
    [GoogleIcons.MedicalServices]: "medical_services",
    [GoogleIcons.MedicalInformation]: "medical_information",
    [GoogleIcons.Medication]: "medication",
    [GoogleIcons.Pill]: "pill",
    [GoogleIcons.Vaccines]: "vaccines",
    [GoogleIcons.Dentistry]: "dentistry",
    [GoogleIcons.Stethoscope]: "stethoscope",
    [GoogleIcons.Cardiology]: "cardiology",
    [GoogleIcons.MonitorHeart]: "monitor_heart",
    [GoogleIcons.BloodPressure]: "blood_pressure",
    [GoogleIcons.Thermometer]: "thermometer",
    [GoogleIcons.Bed]: "bed",
    [GoogleIcons.Bedtime]: "bedtime",
    [GoogleIcons.Sleep]: "sleep",
    [GoogleIcons.SleepScore]: "sleep_score",
    [GoogleIcons.Shower]: "shower",
    [GoogleIcons.Bathtub]: "bathtub",
    [GoogleIcons.CleanHands]: "clean_hands",
    [GoogleIcons.Sanitizer]: "sanitizer",
    [GoogleIcons.Scale]: "scale",
    [GoogleIcons.MonitorWeight]: "monitor_weight",
    [GoogleIcons.FitnessCenter]: "fitness_center",
    [GoogleIcons.Exercise]: "exercise",
    [GoogleIcons.DirectionsRun]: "directions_run",
    [GoogleIcons.Sprint]: "sprint",
    [GoogleIcons.DirectionsWalk]: "directions_walk",
    [GoogleIcons.NordicWalking]: "nordic_walking",
    [GoogleIcons.Hiking]: "hiking",
    [GoogleIcons.DirectionsBike]: "directions_bike",
    [GoogleIcons.PedalBike]: "pedal_bike",
    [GoogleIcons.Pool]: "pool",
    [GoogleIcons.Rowing]: "rowing",
    [GoogleIcons.SportsGymnastics]: "sports_gymnastics",
    [GoogleIcons.SportsMartialArts]: "sports_martial_arts",
    [GoogleIcons.SportsSoccer]: "sports_soccer",
    [GoogleIcons.SportsBasketball]: "sports_basketball",
    [GoogleIcons.SportsTennis]: "sports_tennis",
    [GoogleIcons.SportsVolleyball]: "sports_volleyball",
    [GoogleIcons.SportsHandball]: "sports_handball",
    [GoogleIcons.SportsFootball]: "sports_football",
    [GoogleIcons.SportsRugby]: "sports_rugby",
    [GoogleIcons.SportsGolf]: "sports_golf",
    [GoogleIcons.SportsBaseball]: "sports_baseball",
    [GoogleIcons.Skateboarding]: "skateboarding",
    [GoogleIcons.Surfing]: "surfing",
    [GoogleIcons.WaterDrop]: "water_drop",
    [GoogleIcons.WaterBottle]: "water_bottle",
    [GoogleIcons.LocalDrink]: "local_drink",
    [GoogleIcons.Coffee]: "coffee",
    [GoogleIcons.CoffeeMaker]: "coffee_maker",
    [GoogleIcons.EmojiFoodBeverage]: "emoji_food_beverage",
    [GoogleIcons.Nutrition]: "nutrition",
    [GoogleIcons.Restaurant]: "restaurant",
    [GoogleIcons.RestaurantMenu]: "restaurant_menu",
    [GoogleIcons.LocalDining]: "local_dining",
    [GoogleIcons.DinnerDining]: "dinner_dining",
    [GoogleIcons.LunchDining]: "lunch_dining",
    [GoogleIcons.BreakfastDining]: "breakfast_dining",
    [GoogleIcons.Fastfood]: "fastfood",
    [GoogleIcons.Grocery]: "grocery",
    [GoogleIcons.LocalGroceryStore]: "local_grocery_store",
    [GoogleIcons.Cooking]: "cooking",
    [GoogleIcons.SkilletCooktop]: "skillet_cooktop",
    [GoogleIcons.BakeryDining]: "bakery_dining",
    [GoogleIcons.Cake]: "cake",
    [GoogleIcons.Egg]: "egg",
    [GoogleIcons.RiceBowl]: "rice_bowl",
    [GoogleIcons.RamenDining]: "ramen_dining",
    [GoogleIcons.Icecream]: "icecream",
    [GoogleIcons.Home]: "home",
    [GoogleIcons.HomeAndGarden]: "home_and_garden",
    [GoogleIcons.CleaningServices]: "cleaning_services",
    [GoogleIcons.Cleaning]: "cleaning",
    [GoogleIcons.CleaningBucket]: "cleaning_bucket",
    [GoogleIcons.Mop]: "mop",
    [GoogleIcons.Wash]: "wash",
    [GoogleIcons.Laundry]: "laundry",
    [GoogleIcons.LocalLaundryService]: "local_laundry_service",
    [GoogleIcons.Dishwasher]: "dishwasher",
    [GoogleIcons.Kitchen]: "kitchen",
    [GoogleIcons.Vacuum]: "vacuum",
    [GoogleIcons.Iron]: "iron",
    [GoogleIcons.PottedPlant]: "potted_plant",
    [GoogleIcons.OutdoorGarden]: "outdoor_garden",
    [GoogleIcons.HomeRepairService]: "home_repair_service",
    [GoogleIcons.HomeImprovementAndTools]: "home_improvement_and_tools",
    [GoogleIcons.ToolsPowerDrill]: "tools_power_drill",
    [GoogleIcons.ToolsWrench]: "tools_wrench",
    [GoogleIcons.ToolsLadder]: "tools_ladder",
    [GoogleIcons.Chair]: "chair",
    [GoogleIcons.Garage]: "garage",
    [GoogleIcons.DoorFront]: "door_front",
    [GoogleIcons.Window]: "window",
    [GoogleIcons.Work]: "work",
    [GoogleIcons.Laptop]: "laptop",
    [GoogleIcons.Computer]: "computer",
    [GoogleIcons.Terminal]: "terminal",
    [GoogleIcons.Code]: "code",
    [GoogleIcons.CodeBlocks]: "code_blocks",
    [GoogleIcons.DataObject]: "data_object",
    [GoogleIcons.Book]: "book",
    [GoogleIcons.MenuBook]: "menu_book",
    [GoogleIcons.LibraryBooks]: "library_books",
    [GoogleIcons.School]: "school",
    [GoogleIcons.Language]: "language",
    [GoogleIcons.Translate]: "translate",
    [GoogleIcons.Science]: "science",
    [GoogleIcons.Calculate]: "calculate",
    [GoogleIcons.EditNote]: "edit_note",
    [GoogleIcons.TaskAlt]: "task_alt",
    [GoogleIcons.Checklist]: "checklist",
    [GoogleIcons.CalendarMonth]: "calendar_month",
    [GoogleIcons.Schedule]: "schedule",
    [GoogleIcons.Lightbulb]: "lightbulb",
    [GoogleIcons.Psychology]: "psychology",
    [GoogleIcons.Draw]: "draw",
    [GoogleIcons.DesignServices]: "design_services",
    [GoogleIcons.MusicNote]: "music_note",
    [GoogleIcons.Headphones]: "headphones",
    [GoogleIcons.LibraryMusic]: "library_music",
    [GoogleIcons.Piano]: "piano",
    [GoogleIcons.Palette]: "palette",
    [GoogleIcons.Brush]: "brush",
    [GoogleIcons.VideogameAsset]: "videogame_asset",
    [GoogleIcons.Games]: "games",
    [GoogleIcons.Movie]: "movie",
    [GoogleIcons.Theaters]: "theaters",
    [GoogleIcons.PhotoCamera]: "photo_camera",
    [GoogleIcons.TravelExplore]: "travel_explore",
    [GoogleIcons.Sunny]: "sunny",
    [GoogleIcons.SelfImprovement]: "self_improvement",
    [GoogleIcons.Spa]: "spa",
    [GoogleIcons.Mood]: "mood",
    [GoogleIcons.Nature]: "nature",
    [GoogleIcons.Forest]: "forest",
    [GoogleIcons.Park]: "park",
    [GoogleIcons.BeachAccess]: "beach_access",
    [GoogleIcons.Fireplace]: "fireplace",
    [GoogleIcons.Celebration]: "celebration",
    [GoogleIcons.Pets]: "pets",
    [GoogleIcons.Camping]: "camping",
}

export type GoogleIconSection = {
    name: string
    icons: GoogleIcons[]
}

export const googleIconSections: GoogleIconSection[] = [
    {
        name: "Health",
        icons: [
            GoogleIcons.Favorite,
            GoogleIcons.HealthAndSafety,
            GoogleIcons.HealthMetrics,
            GoogleIcons.MedicalServices,
            GoogleIcons.MedicalInformation,
            GoogleIcons.Medication,
            GoogleIcons.Pill,
            GoogleIcons.Vaccines,
            GoogleIcons.Dentistry,
            GoogleIcons.Stethoscope,
            GoogleIcons.Cardiology,
            GoogleIcons.MonitorHeart,
            GoogleIcons.BloodPressure,
            GoogleIcons.Thermometer,
            GoogleIcons.Bed,
            GoogleIcons.Bedtime,
            GoogleIcons.Sleep,
            GoogleIcons.SleepScore,
            GoogleIcons.Shower,
            GoogleIcons.Bathtub,
            GoogleIcons.CleanHands,
            GoogleIcons.Sanitizer,
            GoogleIcons.Scale,
            GoogleIcons.MonitorWeight
        ],
    },
    {
        name: "Sports and Movement",
        icons: [
            GoogleIcons.FitnessCenter,
            GoogleIcons.Exercise,
            GoogleIcons.DirectionsRun,
            GoogleIcons.Sprint,
            GoogleIcons.DirectionsWalk,
            GoogleIcons.NordicWalking,
            GoogleIcons.Hiking,
            GoogleIcons.DirectionsBike,
            GoogleIcons.PedalBike,
            GoogleIcons.Pool,
            GoogleIcons.Rowing,
            GoogleIcons.SportsGymnastics,
            GoogleIcons.SportsMartialArts,
            GoogleIcons.SportsSoccer,
            GoogleIcons.SportsBasketball,
            GoogleIcons.SportsTennis,
            GoogleIcons.SportsVolleyball,
            GoogleIcons.SportsHandball,
            GoogleIcons.SportsFootball,
            GoogleIcons.SportsRugby,
            GoogleIcons.SportsGolf,
            GoogleIcons.SportsBaseball,
            GoogleIcons.Skateboarding,
            GoogleIcons.Surfing
        ],
    },
    {
        name: "Food and Drinks",
        icons: [
            GoogleIcons.WaterDrop,
            GoogleIcons.WaterBottle,
            GoogleIcons.LocalDrink,
            GoogleIcons.Coffee,
            GoogleIcons.CoffeeMaker,
            GoogleIcons.EmojiFoodBeverage,
            GoogleIcons.Nutrition,
            GoogleIcons.Restaurant,
            GoogleIcons.RestaurantMenu,
            GoogleIcons.LocalDining,
            GoogleIcons.DinnerDining,
            GoogleIcons.LunchDining,
            GoogleIcons.BreakfastDining,
            GoogleIcons.Fastfood,
            GoogleIcons.Grocery,
            GoogleIcons.LocalGroceryStore,
            GoogleIcons.Cooking,
            GoogleIcons.SkilletCooktop,
            GoogleIcons.BakeryDining,
            GoogleIcons.Cake,
            GoogleIcons.Egg,
            GoogleIcons.RiceBowl,
            GoogleIcons.RamenDining,
            GoogleIcons.Icecream
        ],
    },
    {
        name: "Home and Household",
        icons: [
            GoogleIcons.Home,
            GoogleIcons.HomeAndGarden,
            GoogleIcons.CleaningServices,
            GoogleIcons.Cleaning,
            GoogleIcons.CleaningBucket,
            GoogleIcons.Mop,
            GoogleIcons.Wash,
            GoogleIcons.Laundry,
            GoogleIcons.LocalLaundryService,
            GoogleIcons.Dishwasher,
            GoogleIcons.Kitchen,
            GoogleIcons.Vacuum,
            GoogleIcons.Iron,
            GoogleIcons.PottedPlant,
            GoogleIcons.OutdoorGarden,
            GoogleIcons.HomeRepairService,
            GoogleIcons.HomeImprovementAndTools,
            GoogleIcons.ToolsPowerDrill,
            GoogleIcons.ToolsWrench,
            GoogleIcons.ToolsLadder,
            GoogleIcons.Chair,
            GoogleIcons.Garage,
            GoogleIcons.DoorFront,
            GoogleIcons.Window
        ],
    },
    {
        name: "Work and Growth",
        icons: [
            GoogleIcons.Work,
            GoogleIcons.Laptop,
            GoogleIcons.Computer,
            GoogleIcons.Terminal,
            GoogleIcons.Code,
            GoogleIcons.CodeBlocks,
            GoogleIcons.DataObject,
            GoogleIcons.Book,
            GoogleIcons.MenuBook,
            GoogleIcons.LibraryBooks,
            GoogleIcons.School,
            GoogleIcons.Language,
            GoogleIcons.Translate,
            GoogleIcons.Science,
            GoogleIcons.Calculate,
            GoogleIcons.EditNote,
            GoogleIcons.TaskAlt,
            GoogleIcons.Checklist,
            GoogleIcons.CalendarMonth,
            GoogleIcons.Schedule,
            GoogleIcons.Lightbulb,
            GoogleIcons.Psychology,
            GoogleIcons.Draw,
            GoogleIcons.DesignServices
        ],
    },
    {
        name: "Rest and Well-being",
        icons: [
            GoogleIcons.MusicNote,
            GoogleIcons.Headphones,
            GoogleIcons.LibraryMusic,
            GoogleIcons.Piano,
            GoogleIcons.Palette,
            GoogleIcons.Brush,
            GoogleIcons.VideogameAsset,
            GoogleIcons.Games,
            GoogleIcons.Movie,
            GoogleIcons.Theaters,
            GoogleIcons.PhotoCamera,
            GoogleIcons.TravelExplore,
            GoogleIcons.Sunny,
            GoogleIcons.SelfImprovement,
            GoogleIcons.Spa,
            GoogleIcons.Mood,
            GoogleIcons.Nature,
            GoogleIcons.Forest,
            GoogleIcons.Park,
            GoogleIcons.BeachAccess,
            GoogleIcons.Fireplace,
            GoogleIcons.Celebration,
            GoogleIcons.Pets,
            GoogleIcons.Camping
        ],
    }
]
